#dataset: "NYU" # "kitti", "kitti_360"
dataset: "NYU"

kitti_root: '/path/to/semantic_kitti'
kitti_preprocess_root: '/path/to/kitti/preprocess/folder'
kitti_logdir: '/path/to/semantic_kitti/logdir'

NYU_root: '/root/autodl-tmp/DATA/NDCscene_NYU/depthbin'
NYU_preprocess_root: '/root/autodl-tmp/DATA/NDCscene_NYU/preprocess'

enable_log: true
exp_prefix: "exp"
logdir: '/root/autodl-tmp/NDCScene_dev_coord/ndcscene/exp/trial_lr_0.1_1_xybr_3'
output_path: '/root/autodl-tmp/NDCScene_dev_coord/ndcscene/exp/trial_lr_0.1_1_xybr_3/output'

num_workers_per_gpu: 3 
batch_size: 2
n_gpus: 2
run: 1
lr: 1e-4
weight_decay: 1e-4
milestones: [20, ]
max_epochs: 30

resize: false

frustum_size: 8
n_relations: 4
context_prior: true
aux_ssc_loss: false

basemodel_name: tf_efficientnet_b7_ns

CE_ssc_loss: true

relation_loss: true
sem_scal_loss: true
geo_scal_loss: true
fp_loss: true
miou_loss: false





